=== taobao/nginx-docs-cn/dtd/menu.dtd
<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!ELEMENT  menus        (menu+) >

<!ELEMENT  menu         (item+) >
<!ATTLIST  menu
           lang         CDATA #REQUIRED
>

<!ELEMENT  item         (#PCDATA) >
<!ATTLIST  item
           href         CDATA #IMPLIED
           lang         CDATA #IMPLIED
           year         CDATA #IMPLIED
           switchlang   CDATA #IMPLIED
>

=== taobao/nginx-docs-cn/xml/menu.xml
<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE menus SYSTEM "../dtd/menu.dtd">

<menus>

<menu lang="cn">

<item href="/en/" switchlang="en"> english </item>
<item href="/ru/" switchlang="ru"> русский </item>
<item />

<item> 简体中文 </item>
<item href="/he/" switchlang="he"> עברית </item>
<item href="/ja/" switchlang="ja"> 日本語 </item>
<item href="/tr/" switchlang="tr"> türkçe </item>
<item />

<item href="/" lang="en"> 新闻 </item>
<item href="/cn/"> nginx 介绍 </item>
<item href="/en/download.html" lang="en"> 下载 </item>
<item href="/en/security_advisories.html" lang="en"> 安全漏洞 </item>
<item href="/cn/docs/"> 文档 </item>
<item href="/cn/docs/faq.html"> FAQ </item>
<item href="/en/links.html" lang="en"> 外部连接 </item>
<item href="/en/books.html" lang="en"> 书籍 </item>
<item href="/en/support.html" lang="en"> 支持 </item>
<item href="/en/donation.html" lang="en"> 捐献 </item>
<item />

<item href="http://trac.nginx.org/nginx"> trac </item>
<item href="http://wiki.nginx.org/"> wiki </item>
<item href="http://twitter.com/nginxorg"> twitter </item>
<item href="http://www.nginx.com/"> nginx.com </item>

</menu>


<menu lang="en">

<item> english </item>
<item href="/ru/" switchlang="ru"> русский </item>
<item />

<item href="/cn/" switchlang="cn"> 简体中文 </item>
<item href="/he/" switchlang="he"> עברית </item>
<item href="/ja/" switchlang="ja"> 日本語 </item>
<item href="/tr/" switchlang="tr"> türkçe </item>
<item />

<item href="/"> news </item>
<item href="2011.html" year="2011" />
<item href="2010.html" year="2010" />
<item href="2009.html" year="2009" />
<item year="" />

<item href="/en/"> about </item>
<item href="/en/download.html"> download </item>
<!--
<item href="/en/getting_started.html"> getting started </item>
-->
<item href="/en/security_advisories.html"> security advisories </item>
<item href="/en/docs/"> documentation </item>
<item href="/en/pgp_keys.html"> pgp keys </item>
<!--
<item href="/en/docs/reference.html"> reference </item>
-->
<item href="/en/docs/faq.html"> faq </item>
<item href="/en/links.html"> links </item>
<item href="/en/books.html"> books </item>
<item href="/en/support.html"> support </item>
<item href="/en/donation.html"> donation </item>
<item />

<item href="http://trac.nginx.org/nginx"> trac </item>
<item href="http://wiki.nginx.org/"> wiki </item>
<item href="http://twitter.com/nginxorg"> twitter </item>
<item href="http://www.nginx.com/"> nginx.com </item>

</menu>


<menu lang="he">

<item href="/en/" switchlang="en"> english </item>
<item href="/ru/" switchlang="ru"> русский </item>
<item />

<item href="/cn/" switchlang="cn"> 简体中文 </item>
<item> עברית </item>
<item href="/ja/" switchlang="ja"> 日本語 </item>
<item href="/tr/" switchlang="tr"> türkçe </item>
<item />

<item href="/" lang="אנגלית"> חדשות </item>
<item href="/he/"> אודות </item>
<item href="/en/download.html" lang="אנגלית"> הורדה </item>
<item href="/en/security_advisories.html" lang="אנגלית"> דיווחי אבטחה </item>
<item href="/he/docs/"> תיעוד </item>
<item href="/en/docs/faq.html" lang="אנגלית"> שאלות נפוצות </item>
<item href="/en/links.html" lang="אנגלית"> קישורים </item>
<item href="/en/support.html" lang="אנגלית"> תמיכה </item>
<item />

<item href="http://trac.nginx.org/nginx"> trac </item>
<item href="http://wiki.nginx.org/"> wiki </item>
<item href="http://twitter.com/nginxorg"> twitter </item>
<item href="http://www.nginx.com/"> nginx.com </item>

</menu>


<menu lang="ja">

<item href="/en/" switchlang="en"> english </item>
<item href="/ru/" switchlang="ru"> русский </item>
<item />

<item href="/cn/" switchlang="cn"> 简体中文 </item>
<item href="/he/" switchlang="he"> עברית </item>
<item> 日本語 </item>
<item href="/tr/" switchlang="tr"> türkçe </item>
<item />

<item href="/" lang="en"> ニュース </item>
<item href="/ja/"> nginx について </item>
<item href="/en/download.html" lang="en"> ダウンロード </item>
<item href="/en/security_advisories.html" lang="en"> セキュリティ情報 </item>
<item href="/ja/docs/"> ドキュメント </item>
<item href="/ja/docs/faq.html"> faq </item>
<item href="/en/links.html" lang="en"> リンク </item>
<item href="/en/books.html" lang="en"> 本 </item>
<item href="/en/support.html" lang="en"> サポート </item>
<item />

<item href="http://trac.nginx.org/nginx"> trac </item>
<item href="http://wiki.nginx.org/"> wiki </item>
<item href="http://twitter.com/nginxorg"> twitter </item>
<item href="http://www.nginx.com/"> nginx.com </item>

</menu>


<menu lang="ru">

<item href="/en/" switchlang="en"> english </item>
<item> русский </item>
<item />

<item href="/cn/" switchlang="cn"> 简体中文 </item>
<item href="/he/" switchlang="he"> עברית </item>
<item href="/ja/" switchlang="ja"> 日本語 </item>
<item href="/tr/" switchlang="tr"> türkçe </item>
<item />

<item href="/" lang="en"> новости </item>
<item href="/ru/"> об nginx </item>
<item href="/ru/download.html"> скачать </item>
<item href="/en/security_advisories.html" lang="en"> безопасность </item>
<item href="/en/pgp_keys.html" lang="en"> pgp ключи </item>
<item href="/ru/docs/"> документация </item>
<item href="/ru/docs/faq.html"> faq </item>
<item href="/en/links.html" lang="en"> ссылки </item>
<item href="/en/books.html" lang="en"> книги </item>
<item href="/ru/support.html"> поддержка </item>
<item href="/en/donation.html" lang="en"> пожертвования </item>
<item />

<item href="http://trac.nginx.org/nginx"> trac </item>
<item href="http://wiki.nginx.org/"> wiki </item>
<item href="http://twitter.com/nginxorg"> twitter </item>
<item href="http://www.nginx.com/"> nginx.com </item>

</menu>


<menu lang="tr">

<item href="/en/" switchlang="en"> english </item>
<item href="/ru/" switchlang="ru"> русский </item>
<item />

<item href="/cn/" switchlang="cn"> 简体中文 </item>
<item href="/he/" switchlang="he"> עברית </item>
<item href="/ja/" switchlang="ja"> 日本語 </item>
<item> türkçe </item>
<item />

<item href="/" lang="ing"> haberler </item>
<item href="/tr/"> hakkında </item>
<item href="/en/download.html" lang="ing"> indir </item>
<item href="/en/security_advisories.html" lang="ing">
      güvenlik tavsiyeleri </item>
<item href="/tr/docs/"> dökümantasyon </item>
<item href="/tr/docs/faq.html"> sss </item>
<item href="/en/links.html" lang="ing"> bağlantılar </item>
<item href="/en/books.html" lang="ing"> kitaplar </item>
<item href="/en/support.html" lang="ing"> destek </item>
<item />

<item href="http://trac.nginx.org/nginx"> trac </item>
<item href="http://wiki.nginx.org/"> wiki </item>
<item href="http://twitter.com/nginxorg"> twitter </item>
<item href="http://www.nginx.com/"> nginx.com </item>

</menu>

</menus>
