=== taobao/nginx-docs-cn/dtd/module.dtd
<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->


<!ELEMENT   module      (section+) >
<!ATTLIST   module
            name        CDATA #REQUIRED
            link        CDATA #REQUIRED
            lang        CDATA #REQUIRED
            rev         CDATA #IMPLIED
            translator  CDATA #IMPLIED
            toc         (yes | no) "yes"
>

<!ELEMENT   section     (directive | para)+ >
<!ATTLIST   section
            id          ID #REQUIRED
            name        CDATA #IMPLIED
>

<!ELEMENT   directive   (syntax+, default+, context+, appeared-in*, para+) >
<!ATTLIST   directive
            name        ID #REQUIRED
>

<!ELEMENT   syntax      (#PCDATA | literal | value)* >
<!ATTLIST   syntax
            block       (yes | no) "no"
>

<!ELEMENT   default     (#PCDATA)* >

<!ELEMENT   context     (#PCDATA)* >

<!ELEMENT   appeared-in (#PCDATA)* >

<!ELEMENT   para        (#PCDATA | c-def | c-func | command |
                         emphasis | example | header | http-status | link |
                         list | literal | note | path | value | var)* >

<!ELEMENT   c-def       (#PCDATA)* >

<!ELEMENT   c-func      (#PCDATA)* >

<!ELEMENT   command     (#PCDATA)* >

<!ELEMENT   emphasis    (#PCDATA | value)* >

<!ELEMENT   example     (#PCDATA | value | emphasis)* >

<!ELEMENT   header      (#PCDATA | value)* >

<!ELEMENT   http-status EMPTY >
<!ATTLIST   http-status
            code        CDATA #REQUIRED
            text        CDATA #IMPLIED
>

<!ELEMENT   link        (#PCDATA)* >
<!ATTLIST   link
            doc         CDATA #IMPLIED
            id          CDATA #IMPLIED
            url         CDATA #IMPLIED
>

<!ELEMENT   list        (listitem+ | (tag-name | tag-desc)+) >
<!ATTLIST   list
            type        (bullet | enum | tag) #REQUIRED
            compact     (yes | no) "yes"
>

<!ELEMENT   listitem    ANY >
<!ATTLIST   listitem
            id          ID #IMPLIED
>

<!ELEMENT   tag-name    ANY >
<!ATTLIST   tag-name
            id          ID #IMPLIED
>

<!ELEMENT   tag-desc    ANY >

<!ELEMENT   literal     (#PCDATA | value)* >

<!ELEMENT   note        ANY >

<!ELEMENT   path        (#PCDATA)* >

<!ELEMENT   value       (#PCDATA)* >

<!ELEMENT   var         (#PCDATA)* >

<!ENTITY    nbsp        "&#xA0;" >
<!ENTITY    mdash       "&nbsp;- " >

=== taobao/nginx-docs-cn/xml/ru/docs/http/ngx_http_index_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Модуль ngx_http_index_module"
        link="/ru/docs/http/ngx_http_index_module.html"
        lang="ru"
        rev="2">

<section id="summary">

<para>
Модуль <literal>ngx_http_index_module</literal> обслуживает запросы,
оканчивающиеся слэшом (‘<literal>/</literal>’).
Такие запросы также могут обслуживаться модулями
<link doc="ngx_http_autoindex_module.xml">ngx_http_autoindex_module</link>
и
<link doc="ngx_http_random_index_module.xml">ngx_http_random_index_module</link>.
</para>

</section>


<section id="example" name="Пример конфигурации">

<para>
<example>
location / {
    index index.$geo.html index.html;
}
</example>
</para>

</section>


<section id="directives" name="Директивы">

<directive name="index">
<syntax><value>файл</value> ...</syntax>
<default>index.html</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Определяет файлы, которые будут использоваться в качестве индекса.
В имени файла можно использовать переменные.
Наличие файлов проверяется в порядке их перечисления.
В конце списка может стоять файл с абсолютным путём.
Пример:
<example>
index index.$geo.html index.0.html /index.html;
</example>
</para>

<para>
Необходимо иметь в виду, что при использовании индексного файла делается
внутреннее перенаправление и запрос может быть обработан уже в другом
location’е.
Например, в такой конфигурации:
<example>
location = / {
    index index.html;
}

location / {
    ...
}
</example>
запрос “<literal>/</literal>” будет фактически обработан во
втором location’е как “<literal>/index.html</literal>”.
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/ru/docs/http/ngx_http_charset_module.xml
<?xml version="1.0"?>

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Модуль ngx_http_charset_module"
        link="/ru/docs/http/ngx_http_charset_module.html"
        lang="ru">

<section id="summary">

<para>
Модуль <literal>ngx_http_charset_module</literal> добавляет указанную
кодировку в поле <header>Content-Type</header> заголовка ответа.
Кроме того, модуль может перекодировать данные из одной кодировки в другую
с некоторыми ограничениями:
<list type="bullet">

<listitem>
перекодирование осуществляется только в одну сторону — от сервера к клиенту,
</listitem>

<listitem>
перекодироваться могут только однобайтные кодировки
</listitem>

<listitem>
или однобайтные кодировки в UTF-8 и обратно.
</listitem>

</list>
</para>

</section>


<section id="example" name="Пример конфигурации">

<para>
<example>
    include        conf/koi-win;

    charset        windows-1251;
    source_charset koi8-r;
</example>
</para>

</section>


<section id="directives" name="Директивы">

<directive name="charset">
<syntax><value>кодировка</value> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if в location</context>

<para>
Добавляет указанную кодировку в поле <header>Content-Type</header>
заголовка ответа.
Если эта кодировка отличается от указанной в директиве
<link id="source_charset"/>, то выполняется перекодирование.
</para>

<para>
Параметр <literal>off</literal> отменяет добавление кодировки
в поле <header>Content-Type</header> заголовка ответа.
</para>

<para>
Кодировка может быть задана с помощью переменной:
<example>
charset $charset;
</example>
В этом случае необходимо, чтобы все возможные значения переменной
присутствовали хотя бы один раз в любом месте конфигурации в виде
директив <link id="charset_map"/>, <link id="charset"/> или
<link id="source_charset"/>.
Для кодировок <literal>utf-8</literal>, <literal>windows-1251</literal>
и <literal>koi8-r</literal> для этого достаточно включить в конфигурацию
файлы <path>conf/koi-win</path>, <path>conf/koi-utf</path> и
<path>conf/win-utf</path>.
Для других кодировок можно просто сделать фиктивную таблицу перекодировки,
например:
<example>
charset_map iso-8859-5 _ { }
</example>
</para>

</directive>


<directive name="charset_map">
<syntax block="yes"><value>кодировка1</value> <value>кодировка2</value></syntax>
<default/>
<context>http</context>

<para>
Описывает таблицу перекодирования из одной кодировки в другую.
Таблица для обратного перекодирования строится на основании тех же данных.
Коды символов задаются в шестнадцатеричном виде.
Неописанные символы в пределах 80-FF заменяются на “<literal>?</literal>”.
При перекодировании из UTF-8 символы, отсутствующие в однобайтной кодировке,
заменяются на “<literal>&amp;#XXXX;</literal>”.
</para>

<para>
Пример:
<example>
charset_map koi8-r windows-1251 {
    C0 FE ; # small yu
    C1 E0 ; # small a
    C2 E1 ; # small b
    C3 F6 ; # small ts
    ...
}
</example>
</para>

<para>
При описании таблицы перекодирования в UTF-8, коды кодировки UTF-8 должны
быть указаны во второй колонке, например:
<example>
charset_map koi8-r utf-8 {
    C0 D18E ; # small yu
    C1 D0B0 ; # small a
    C2 D0B1 ; # small b
    C3 D186 ; # small ts
    ...
}
</example>
</para>

<para>
Полные таблицы преобразования из <literal>koi8-r</literal> в
<literal>windows-1251</literal> и из <literal>koi8-r</literal> и
<literal>windows-1251</literal> в <literal>utf-8</literal>
входят в дистрибутив и находятся в файлах <path>conf/koi-win</path>,
<path>conf/koi-utf</path> и <path>conf/win-utf</path>.
</para>

</directive>


<directive name="charset_types">
<syntax><value>mime-тип</value> ...</syntax>
<default>text/html text/xml text/plain text/vnd.wap.wml
application/x-javascript application/rss+xml</default>
<context>http</context>
<context>server</context>
<context>location</context>
<appeared-in>0.7.9</appeared-in>

<para>
Разрешает работу модуля в ответах с указанными MIME-типами
в дополнение к “<literal>text/html</literal>”.
</para>

</directive>


<directive name="override_charset">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if в location</context>

<para>
Определяет, выполнять ли перекодирование для ответов,
полученных от проксированного сервера или от FastCGI-сервера,
если в ответах уже указана кодировка в поле <header>Content-Type</header>
заголовка ответа.
Если перекодирование разрешено, то в качестве исходной кодировки
используется кодировка, указанная в полученном ответе.
<note>
Необходимо отметить, что если ответ был получен в подзапросе,
то, независимо от значения директивы <literal>override_charset</literal>,
всегда выполняется перекодирование из кодировки ответа в кодировку
основного запроса.
</note>
</para>

</directive>


<directive name="source_charset">
<syntax><value>кодировка</value></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if в location</context>

<para>
Задаёт исходную кодировку ответа.
Если эта кодировка отличается от указанной в директиве
<link id="charset"/>, то выполняется перекодирование.
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/http/ngx_http_geo_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="ngx_http_geo_module 模块"
        link="/cn/docs/http/ngx_http_geo_module.html"
        lang="cn"
        translator="cfsego"
        rev="1">

<section id="summary">

<para>
<literal>ngx_http_geo_module</literal> 模块创建变量，并根据客户端IP地址对变量赋值。
</para>

</section>


<section id="example" name="配置示例">

<para>
<example>
geo $geo {
    default        0;
    127.0.0.1/32   2;
    192.168.1.0/24 1;
    10.1.0.0/16    1;
}
</example>
</para>

</section>


<section id="directives" name="指令">

<directive name="geo">
<syntax block="yes">[<value>$address</value>] <value>$variable</value></syntax>
<default/>
<context>http</context>

<para>
定义从指定的变量获取客户端的IP地址。默认情况下，nginx从<var>$remote_addr</var>变量取得客户端IP地址，但也可以从其他变量获得（0.7.27版），比如：
<example>
geo $arg_remote_addr $geo {
    ...;
}
</example>
如果该变量的值不能代表一个合法的IP地址，那么nginx将使用地址“<literal>255.255.255.255</literal>”。
</para>

<para>
nginx通过CIDR或者地址段（0.7.23版）来描述地址，同时支持下面的特殊参数：
<list type="tag">

<tag-name><literal>delete</literal></tag-name>
<tag-desc>
删除指定网络（0.7.23版）。
</tag-desc>

<tag-name><literal>default</literal></tag-name>
<tag-desc>
如果客户端地址不能匹配任意一个定义的地址，nginx将使用此值。
如果使用CIDR，可以用“<literal>0.0.0.0/0</literal>”代替<literal>default</literal>。
</tag-desc>

<tag-name><literal>include</literal></tag-name>
<tag-desc>
包含一个定义地址和值的文件。可以多次包含。
</tag-desc>

<tag-name><literal>proxy</literal></tag-name>
<tag-desc>
定义可信地址（0.8.7，0.7.63版）。
如果请求来自可信地址，nginx将使用其<header>X-Forwarded-For</header>头来获得地址。
相对于普通地址，可信地址是顺序检测的。
<note>
从1.3.0和1.2.1版本起，nginx开始支持IPv6地址。
</note>
</tag-desc>

<tag-name><literal>proxy_recursive</literal></tag-name>
<tag-desc>
开启递归查找地址（1.3.0，1.2.1版）。
如果关闭递归查找，在客户端地址与某个可信地址匹配时，nginx将使用<header>X-Forwarded-For</header>中的最后一个地址来代替原始客户端地址。
如果开启递归查找，在客户端地址与某个可信地址匹配时，nginx将使用<header>X-Forwarded-For</header>中最后一个与所有可信地址都不匹配的地址来代替原始客户端地址。
</tag-desc>

<tag-name><literal>ranges</literal></tag-name>
<tag-desc>
指示地址将定义为地址段的形式（0.7.23版）。这个参数应该第一个被定义。为了加速装载地址库，地址应按升序定义。
</tag-desc>

</list>
</para>

<para>
举例：
<example>
geo $country {
    default        ZZ;
    include        conf/geo.conf;
    delete         127.0.0.0/16;
    proxy          192.168.100.0/24;
    proxy          2001:0db8::/32;

    127.0.0.0/24   US;
    127.0.0.1/32   RU;
    10.1.0.0/16    RU;
    192.168.1.0/24 UK;
}
</example>
</para>

<para>
<path>conf/geo.conf</path>文件中可能包含下列文本行：
<example>
10.2.0.0/16    RU;
192.168.2.0/24 RU;
</example>
</para>

<para>
nginx将使用能最精确匹配客户端地址的配置中定义的值。比如，对于地址127.0.0.1，nginx会选取“<literal>RU</literal>”而非“<literal>US</literal>”，作为变量值。
</para>

<para>
地址段的例子：
<example>
geo $country {
    ranges;
    default                   ZZ;
    127.0.0.0-127.0.0.0       US;
    127.0.0.1-127.0.0.1       RU;
    127.0.0.1-127.0.0.255     US;
    10.1.0.0-10.1.255.255     RU;
    192.168.1.0-192.168.1.255 UK;
}
</example>
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/http/ngx_http_limit_conn_module.xml
<?xml version="1.0"?>

<!-- 
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  Copyright (C) G_will <g_will@ieqi.com>
-->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="ngx_http_limit_conn_module 模块"
        link="/cn/docs/http/ngx_http_limit_conn_module.html"
        lang="cn"
        rev="1"
        translator="G_will">

<section id="summary">

<para>
<literal>ngx_http_limit_conn_module</literal> 模块可以按照定义的键限定每个键值的连接数。特别的，可以设定单一 IP 来源的连接数。
</para>

<para>
并不是所有的连接都会被模块计数；只有那些正在被处理的请求（这些请求的头信息已被完全读入）所在的连接才会被计数。
</para>

</section>


<section id="example" name="配置范例">

<para>
<example>
http {
    limit_conn_zone $binary_remote_addr zone=addr:10m;

    ...

    server {

        ...

        location /download/ {
            limit_conn addr 1;
        }
</example>
</para>

</section>


<section id="directives" name="指令">

<directive name="limit_conn">
<syntax><value>zone</value> <value>number</value></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
指定一块已经设定的共享内存空间，以及每个给定键值的最大连接数。当连接数超过最大连接数时，服务器将会返回
<http-status code="503" text="Service Temporarily Unavailable"/>
错误。比如，如下配置
<example>
limit_conn_zone $binary_remote_addr zone=addr:10m;

server {
    location /download/ {
        limit_conn addr 1;
    }
</example>
表示，同一 IP 同一时间只允许有一个连接。
</para>

<para>
当多个 <literal>limit_conn</literal> 指令被配置时，所有的连接数限制都会生效。比如，下面配置不仅会限制单一IP来源的连接数，同时也会限制单一虚拟服务器的总连接数：
<example>
limit_conn_zone $binary_remote_addr zone=perip:10m;
limit_conn_zone $server_name zone=perserver:10m;

server {
    ...
    limit_conn perip 10;
    limit_conn perserver 100;
}
</example>

</para>

<para>
如果当前配置层级没有<literal>limit_conn</literal>指令，将会从更高层级继承连接限制配置。
</para>

</directive>


<directive name="limit_conn_log_level">
<syntax>
<literal>info</literal> |
<literal>notice</literal> |
<literal>warn</literal> |
<literal>error</literal></syntax>
<default>error</default>
<context>http</context>
<context>server</context>
<context>location</context>
<appeared-in>0.8.18</appeared-in>

<para>
指定当连接数超过设定的最大连接数，服务器限制连接时的日志等级。
</para>

</directive>


<directive name="limit_conn_zone">
<syntax>
    <value>$variable</value>
    <literal>zone</literal>=<value>name</value>:<value>size</value></syntax>
<default/>
<context>http</context>

<para>
设定保存各个键的状态的共享内存空间的参数。键的状态中保存了当前连接数。键的值可以是特定变量的任何非空值（空值将不会被考虑）。
使用范例：
<example>
limit_conn_zone $binary_remote_addr zone=addr:10m;
</example>
这里，设置客户端的IP地址作为键。注意，这里使用的是<var>$binary_remote_addr</var>变量，而不是<var>$remote_addr</var>变量。<var>$remote_addr</var>变量的长度为7字节到15字节不等，而存储状态在32位平台中占用32字节或64字节，在64位平台中占用64字节。而<var>$binary_remote_addr</var>变量的长度是固定的4字节，存储状态在32位平台中占用32字节或64字节，在64位平台中占用64字节。一兆字节的共享内存空间可以保存3.2万个32位的状态，1.6万个64位的状态。如果共享内存空间被耗尽，服务器将会对后续所有的请求返回
<http-status code="503" text="Service Temporarily Unavailable"/>
错误。
</para>

</directive>


<directive name="limit_zone">
<syntax>
    <value>name</value>
    <value>$variable</value>
    <value>size</value></syntax>
<default/>
<context>http</context>

<para>
这条指令在 1.1.8 版本中已经被废弃，应该使用等效的<link id="limit_conn_zone"/>指令。该指令的语法也有变化：
<note>
<literal>limit_conn_zone</literal>
<value>$variable</value>
<literal>zone</literal>=<value>name</value>:<value>size</value>;
</note>
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/http/ngx_http_auth_basic_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  Copyright (C) moonbingbing@gmail.com
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="ngx_http_auth_basic_module模块"
        link="/cn/docs/http/ngx_http_auth_basic_module.html"
        lang="cn"
        rev="1"
        translator="WenMing">

<section id="summary">

<para>
模块<literal>ngx_http_auth_basic_module</literal> 允许使用“HTTP基本认证”协议验证用户名和密码来限制对资源的访问。
</para>

<para>
也可以通过
<link doc="ngx_http_auth_basic_module.xml">地址</link>来限制访问。
使用<link doc="ngx_http_core_module.xml" id="satisfy"/> 指令就能同时通过地址和密码来限制访问。
</para>

</section>


<section id="example" name="配置范例">

<para>
<example>
location / {
    auth_basic           "closed site";
    auth_basic_user_file conf/htpasswd;
}
</example>
</para>

</section>


<section id="directives" name="指令">

<directive name="auth_basic">
<syntax><value>string</value> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>
<context>limit_except</context>

<para>
开启使用“HTTP基本认证”协议的用户名密码验证。
指定的参数被用作 <value>域</value>。
参数<literal>off</literal>可以取消继承自上一个配置等级
<literal>auth_basic</literal> 指令的影响。
</para>

</directive>


<directive name="auth_basic_user_file">
<syntax><value>file</value></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>
<context>limit_except</context>

<para>
指定保存用户名和密码的文件，格式如下：
<example>
# comment
name1:password1
name2:password2:comment
name3:password3
</example>
</para>

<para>
密码应该使用<c-func>crypt</c-func>函数加密。
可以用Apache发行包中的<command>htpasswd</command>命令来创建此类文件。
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/ru/docs/http/ngx_http_autoindex_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Модуль ngx_http_autoindex_module"
        link="/ru/docs/http/ngx_http_autoindex_module.html"
        lang="ru"
        rev="2">

<section id="summary">

<para>
Модуль <literal>ngx_http_autoindex_module</literal> обслуживает запросы,
оканчивающиеся слэшом (‘<literal>/</literal>’), и выдаёт листинг каталога.
Обычно запрос попадает к модулю <literal>ngx_http_autoindex_module</literal>,
когда модуль <link doc="ngx_http_index_module.xml">ngx_http_index_module</link>
не нашёл индексный файл.
</para>

</section>


<section id="example" name="Пример конфигурации">

<para>
<example>
location / {
    autoindex on;
}
</example>
</para>

</section>


<section id="directives" name="Директивы">

<directive name="autoindex">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Разрешает или запрещает вывод листинга каталога.
</para>

</directive>


<directive name="autoindex_exact_size">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>on</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Определяет, как выводить размеры файлов в листинге
каталога — точно, или округляя до килобайт, мегабайт и гигабайт.
</para>

</directive>


<directive name="autoindex_localtime">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Определяет, в какой временной зоне выводить время в листинге
каталога — в локальной или в UTC.
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/mail/ngx_mail_imap_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) 2006, 2007 Anton Yuzhaninov
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Module ngx_mail_imap_module"
        link="/en/docs/mail/ngx_mail_imap_module.html"
        lang="en"
        rev="1">

<section id="directives" name="Directives">

<directive name="imap_auth">
<syntax><value>method</value> ...</syntax>
<default>plain</default>
<context>mail</context>
<context>server</context>

<para>
Sets permitted methods of authentication for IMAP clients.
Supported methods are:
<list type="tag">

<tag-name><literal>login</literal></tag-name>
<tag-desc>
<link url="http://tools.ietf.org/html/draft-murchison-sasl-login-00">AUTH=LOGIN</link>
</tag-desc>

<tag-name><literal>plain</literal></tag-name>
<tag-desc>
<link url="http://tools.ietf.org/html/rfc4616">AUTH=PLAIN</link>
</tag-desc>

<tag-name><literal>cram-md5</literal></tag-name>
<tag-desc>
<link url="http://tools.ietf.org/html/rfc2195">AUTH=CRAM-MD5</link>.
In order for this method to work, the password must be stored unencrypted.
</tag-desc>

</list>
</para>

</directive>


<directive name="imap_capabilities">
<syntax><value>extension</value> ...</syntax>
<default>IMAP4 IMAP4rev1 UIDPLUS</default>
<context>mail</context>
<context>server</context>

<para>
Allows to specify the
<link url="http://tools.ietf.org/html/rfc3501">IMAP protocol</link>
extensions list to be passed to the client upon
issuing the <literal>CAPABILITY</literal> command.
Authentication methods specified in the <link id="imap_auth"/> and
<link url="http://tools.ietf.org/html/rfc2595">STARTTLS</link> directives
are automatically added to this list if the
<link doc="ngx_mail_ssl_module.xml" id="starttls"/> directive is enabled.
</para>

<para>
It makes sense to specify extensions
supported by IMAP backends
to which clients are proxied (if this extensions are related to commands
used after the authentication, when nginx transparently proxies the client
connection to the backend).
</para>

<para>
The current list of standardized extensions is published at the
<link url="http://www.iana.org/assignments/imap4-capabilities">www.iana.org</link>.
</para>

</directive>


<directive name="imap_client_buffer">
<syntax><value>size</value></syntax>
<default>4k|8k</default>
<context>mail</context>
<context>server</context>

<para>
Sets the IMAP commands read buffer size.
By default, the buffer size is equal to one memory page.
This is either 4K or 8K, depending on a platform.
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/en/docs/http/ngx_http_memcached_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Module ngx_http_memcached_module"
        link="/en/docs/http/ngx_http_memcached_module.html"
        lang="en"
        rev="3">

<section id="summary">

<para>
The <literal>ngx_http_memcached_module</literal> module allows to obtain
responses from a memcached server.
The key is set in the <var>$memcached_key</var> variable.
A response should be put in memcached in advance via means that are
external to nginx.
</para>

</section>


<section id="example" name="Example Configuration">

<para>
<example>
server {
    location / {
        set            $memcached_key "$uri?$args";
        memcached_pass host:11211;
        error_page     404 502 504 = @fallback;
    }

    location @fallback {
        proxy_pass     http://backend;
    }
}
</example>
</para>

</section>


<section id="directives" name="Directives">

<directive name="memcached_bind">
<syntax><value>address</value></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>
<appeared-in>0.8.22</appeared-in>

<para>
Forces outgoing connections to a memcached server to originate
from the specified local IP <value>address</value>.
</para>

</directive>


<directive name="memcached_buffer_size">
<syntax><value>size</value></syntax>
<default>4k|8k</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Sets <value>size</value> of the buffer used for reading a response
received from the memcached server.
A response is passed to a client synchronously, immediately as it is received.
</para>

</directive>


<directive name="memcached_connect_timeout">
<syntax><value>time</value></syntax>
<default>60s</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Defines a timeout for establishing a connection with the memcached server.
It should be noted that this timeout cannot usually exceed 75 seconds.
</para>

</directive>


<directive name="memcached_gzip_flag">
<syntax><value>flag</value></syntax>
<default></default>
<context>http</context>
<context>server</context>
<context>location</context>
<appeared-in>1.3.6</appeared-in>

<para>
Enables the test for the <value>flag</value> presence in the memcached
server response and sets the request header field
“<literal>Content-Encoding</literal>” to “<literal>gzip</literal>”
if the flag is set.
</para>

</directive>


<directive name="memcached_next_upstream">
<syntax>
    <literal>error</literal> |
    <literal>timeout</literal> |
    <literal>invalid_response</literal> |
    <literal>not_found</literal> |
    <literal>off</literal>
    ...</syntax>
<default>error timeout</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Specifies in which cases a request should be passed to the next server:
<list type="tag">

<tag-name><literal>error</literal></tag-name>
<tag-desc>an error occurred while establishing a connection with the
server, passing it a request, or reading the response header;</tag-desc>

<tag-name><literal>timeout</literal></tag-name>
<tag-desc>a timeout has occurred while establishing a connection with the
server, passing it a request, or reading the response header;</tag-desc>

<tag-name><literal>invalid_response</literal></tag-name>
<tag-desc>a server returned empty or invalid response;</tag-desc>

<tag-name><literal>not_found</literal></tag-name>
<tag-desc>a response was not found on the server;</tag-desc>

<tag-name><literal>off</literal></tag-name>
<tag-desc>disables passing a request to the next server.</tag-desc>

</list>
</para>

<para>
It should be understood that passing a request to the next server is
only possible if a client was not sent anything yet.
That is, if an error or a timeout occurs in the middle of
transferring a response, fixing this is impossible.
</para>

</directive>


<directive name="memcached_pass">
<syntax><value>address</value></syntax>
<default/>
<context>location</context>
<context>if in location</context>

<para>
Sets an address of the memcached server.
An address can be specified as a domain name or an address, and a port,
for example,
<example>
memcached_pass localhost:11211;
</example>
</para>

<para>
If a domain name resolves to several addresses, all of them will be
used in a round-robin fashion.
In addition, an address can be specified as a
<link doc="ngx_http_upstream_module.xml">server group</link>.
</para>

</directive>


<directive name="memcached_read_timeout">
<syntax><value>time</value></syntax>
<default>60s</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Defines a timeout for reading a response from the memcached server.
A timeout is only set between two successive read operations,
not for the transmission of the whole response.
If a memcached server does not transmit anything within this time,
a connection is closed.
</para>

</directive>


<directive name="memcached_send_timeout">
<syntax><value>time</value></syntax>
<default>60s</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Sets a timeout for transmitting a request to the memcached server.
A timeout is only set between two successive write operations,
not for the transmission of the whole request.
If a memcached server does not receive anything within this time,
a connection is closed.
</para>

</directive>

</section>

</module>
