=== taobao/nginx-docs-cn/dtd/module.dtd
<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->


<!ELEMENT   module      (section+) >
<!ATTLIST   module
            name        CDATA #REQUIRED
            link        CDATA #REQUIRED
            lang        CDATA #REQUIRED
            rev         CDATA #IMPLIED
            translator  CDATA #IMPLIED
            toc         (yes | no) "yes"
>

<!ELEMENT   section     (directive | para)+ >
<!ATTLIST   section
            id          ID #REQUIRED
            name        CDATA #IMPLIED
>

<!ELEMENT   directive   (syntax+, default+, context+, appeared-in*, para+) >
<!ATTLIST   directive
            name        ID #REQUIRED
>

<!ELEMENT   syntax      (#PCDATA | literal | value)* >
<!ATTLIST   syntax
            block       (yes | no) "no"
>

<!ELEMENT   default     (#PCDATA)* >

<!ELEMENT   context     (#PCDATA)* >

<!ELEMENT   appeared-in (#PCDATA)* >

<!ELEMENT   para        (#PCDATA | c-def | c-func | command |
                         emphasis | example | header | http-status | link |
                         list | literal | note | path | value | var)* >

<!ELEMENT   c-def       (#PCDATA)* >

<!ELEMENT   c-func      (#PCDATA)* >

<!ELEMENT   command     (#PCDATA)* >

<!ELEMENT   emphasis    (#PCDATA | value)* >

<!ELEMENT   example     (#PCDATA | value | emphasis)* >

<!ELEMENT   header      (#PCDATA | value)* >

<!ELEMENT   http-status EMPTY >
<!ATTLIST   http-status
            code        CDATA #REQUIRED
            text        CDATA #IMPLIED
>

<!ELEMENT   link        (#PCDATA)* >
<!ATTLIST   link
            doc         CDATA #IMPLIED
            id          CDATA #IMPLIED
            url         CDATA #IMPLIED
>

<!ELEMENT   list        (listitem+ | (tag-name | tag-desc)+) >
<!ATTLIST   list
            type        (bullet | enum | tag) #REQUIRED
            compact     (yes | no) "yes"
>

<!ELEMENT   listitem    ANY >
<!ATTLIST   listitem
            id          ID #IMPLIED
>

<!ELEMENT   tag-name    ANY >
<!ATTLIST   tag-name
            id          ID #IMPLIED
>

<!ELEMENT   tag-desc    ANY >

<!ELEMENT   literal     (#PCDATA | value)* >

<!ELEMENT   note        ANY >

<!ELEMENT   path        (#PCDATA)* >

<!ELEMENT   value       (#PCDATA)* >

<!ELEMENT   var         (#PCDATA)* >

<!ENTITY    nbsp        "&#xA0;" >
<!ENTITY    mdash       "&nbsp;- " >

=== taobao/nginx-docs-cn/xml/en/docs/http/ngx_http_map_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Module ngx_http_map_module"
        link="/en/docs/http/ngx_http_map_module.html"
        lang="en"
        rev="2">

<section id="summary">

<para>
The <literal>ngx_http_map_module</literal> module creates variables
whose values depend on values of other variables.
</para>

</section>


<section id="example" name="Example Configuration">

<para>
<example>
map $http_host $name {
    hostnames;

    default       0;

    example.com   1;
    *.example.com 1;
    example.org   2;
    *.example.org 2;
    .example.net  3;
    wap.*         4;
}

map $http_user_agent $mobile {
    default       0;
    "~Opera Mini" 1;
}
</example>
</para>

</section>


<section id="directives" name="Directives">

<directive name="map">
<syntax block="yes">
    <value>string</value>
    <value>$variable</value></syntax>
<default/>
<context>http</context>

<para>
Creates a new variable whose value
depends on values of one or more of the source variables
specified in the first parameter.
<note>
Before version 0.9.0 only a single variable could be
specified in the first parameter.
</note>
</para>

<para>
<note>
Since variables are evaluated only when used, the mere existence
of even a large number of declared “<literal>map</literal>” variables
does not incur any extra costs for request processing.
</note>
</para>

<para>
Parameters inside the <literal>map</literal> block specify a mapping
between source and resulting values.
</para>

<para>
Source values are specified as strings or regular expressions (0.9.6).
</para>

<para>
A regular expression should either start from the “<literal>~</literal>”
symbol for a case-sensitive matching, or from the “<literal>~*</literal>”
symbols (1.0.4) for case-insensitive matching.
A regular expression can contain named and positional captures
that can later be used in other directives along with the
resulting variable.
</para>

<para>
If a source value matches one of the names of special parameters
described below, it should be prefixed with the “<literal>\</literal>” symbol.
</para>

<para>
The resulting value can be a string
or another variable (0.9.0).
</para>

<para>
The directive also supports three special parameters:
<list type="tag">
<tag-name><literal>default</literal> <value>value</value></tag-name>
<tag-desc>
sets the resulting value if the source value matches none
of the specified variants.
When <literal>default</literal> is not specified, the default
resulting value will be an empty string.
</tag-desc>

<tag-name><literal>hostnames</literal></tag-name>
<tag-desc>
allows to specify hostnames with a prefix or suffix mask, as source
values, for example,
<example>
*.example.com 1;
example.*     1;
</example>
The following two records
<example>
example.com   1;
*.example.com 1;
</example>
can be combined:
<example>
.example.com  1;
</example>
This parameter should be specified before the list of values.
</tag-desc>

<tag-name><literal>include</literal> <value>file</value></tag-name>
<tag-desc>
includes a file with values.
There can be several inclusions.
</tag-desc>

</list>
</para>

<para>
If the source value matches more than one of the specified variants,
e.g. both mask and regular expression match, the first matching
variant will be chosen, in the following order of precedence:
<list type="enum">

<listitem>
string value without a mask
</listitem>

<listitem>
longest string value with a prefix mask,
e.g. “<literal>*.example.com</literal>”
</listitem>

<listitem>
longest string value with a suffix mask,
e.g. “<literal>mail.*</literal>”
</listitem>

<listitem>
first matching regular expression
(in order of appearance in a configuration file)
</listitem>

<listitem>
default value
</listitem>

</list>
</para>

</directive>


<directive name="map_hash_bucket_size">
<syntax><value>size</value></syntax>
<default>32|64|128</default>
<context>http</context>

<para>
Sets the bucket size for the <link id="map"/> variables hash tables.
Default value depends on the size of the processor’s cache line.
Details of setting up hash tables are provided in a separate
<link doc="../hash.xml">document</link>.
</para>

</directive>


<directive name="map_hash_max_size">
<syntax><value>size</value></syntax>
<default>2048</default>
<context>http</context>

<para>
Sets the maximum <value>size</value> of the <link id="map"/> variables
hash tables.
Details of setting up hash tables are provided in a separate
<link doc="../hash.xml">document</link>.
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/http/ngx_http_charset_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="ngx_http_charset_module模块"
        link="/cn/docs/http/ngx_http_charset_module.html"
        lang="cn"
        translator="WenMing"
        rev="1">

<section id="summary">

<para>
<literal>ngx_http_charset_module</literal>模块为响应头的<header>Content-Type</header>添加指定的字符集。 

此外，这个模块可以把数据从一个字符集转换为另一个字符集，但也有以下限制：
<list type="bullet">

<listitem>
只能单向转换，即从服务端到客户端，
</listitem>

<listitem>
只有单字节字符集能被转换
</listitem>

<listitem>
或者单字节字符集和UTF-8之间的互相转换。
</listitem>

</list>
</para>

</section>


<section id="example" name="配置示例">

<para>
<example>
include        conf/koi-win;

charset        windows-1251;
source_charset koi8-r;
</example>
</para>

</section>


<section id="directives" name="指令">

<directive name="charset">
<syntax><value>charset</value> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if in location</context>

<para>
为响应头的<header>Content-Type</header>添加指定的字符集。
如果这个字符集和<link id="source_charset"/>指令设置的字符集不同，就会进行转换。
</para>

<para>
参数<literal>off</literal> 表明不在响应头的<header>Content-Type</header>中添加字符集。
</para>

<para>
字符集可以当作变量来定义：
<example>
charset $charset;
</example>
这种情况下，一个变量所有可能的值，至少使用
<link id="charset_map"/> <link id="charset"/>, 或者
<link id="source_charset"/> 指令中的一种来配置。
对于 <literal>utf-8</literal>, <literal>windows-1251</literal>, 和
<literal>koi8-r</literal> 字符集，在配置中包含
<path>conf/koi-win</path>, <path>conf/koi-utf</path>, 和
<path>conf/win-utf</path>这些文件就足够了。
对于其他字符集，简单地做一个虚构转换表就可以了，
比如：
<example>
charset_map iso-8859-5 _ { }
</example>
</para>

<para>
此外，字符集也可以在响应头的
<header>X-Accel-Charset</header>中设置。
这个功能可以使用
<link doc="ngx_http_proxy_module.xml" id="proxy_ignore_headers"/>
和
<link doc="ngx_http_fastcgi_module.xml" id="fastcgi_ignore_headers"/>
指令来禁用。
</para>

</directive>


<directive name="charset_map">
<syntax block="yes"><value>charset1</value> <value>charset2</value></syntax>
<default/>
<context>http</context>

<para>
描述了从一个字符集到另一个字符集的转换表。
反向转换表使用相同的数据来构建。
字符代码用十六进制表示。
在80-FF范围内不能表示的字符使用 “<literal>?</literal>”替换。
当把UTF-8转换为其他字符集时, 单字节字符集中不能表示的字符使用 “<literal>&amp;#XXXX;</literal>”来替换。
</para>

<para>
示例：
<example>
charset_map koi8-r windows-1251 {
    C0 FE ; # small yu
    C1 E0 ; # small a
    C2 E1 ; # small b
    C3 F6 ; # small ts
    ...
}
</example>
</para>

<para>
当描述一个UTF-8的转换表时，UTF-8的字符集代码应该放在第二列，比如：
<example>
charset_map koi8-r utf-8 {
    C0 D18E ; # small yu
    C1 D0B0 ; # small a
    C2 D0B1 ; # small b
    C3 D186 ; # small ts
    ...
}
</example>
</para>

<para>
发行文件<path>conf/koi-win</path>,
<path>conf/koi-utf</path>, and <path>conf/win-utf</path>中已经提供了从<literal>koi8-r</literal>到
<literal>windows-1251</literal>，从<literal>koi8-r</literal>到<literal>utf-8</literal>，以及从
<literal>windows-1251</literal>到<literal>utf-8</literal>的完整转换表。
</para>

</directive>


<directive name="charset_types">
<syntax><value>mime-type</value> ...</syntax>
<default>text/html text/xml text/plain text/vnd.wap.wml
application/x-javascript application/rss+xml</default>
<context>http</context>
<context>server</context>
<context>location</context>
<appeared-in>0.7.9</appeared-in>

<para>
使模块在响应时能处理除了“<literal>text/html</literal>”之外其他指定的MIME类型。
特殊值“<literal>*</literal>” 匹配任意的MIME类型(0.8.29)。
</para>

</directive>


<directive name="override_charset">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if in location</context>

<para>
对于接收到的代理服务器或者FastCGI服务器的响应头中<header>Content-Type</header>已经带有字符集的情况，确定是否进行字符集转换。
如果开启转换，接收到的响应中指定的字符集会被当作原始字符集。
<note>
需要注意的是，如果在子请求中接收到的应答，始终会将应答的字符集转换为主请求的字符集，无论<literal>override_charset</literal>
指令是否开启。
</note>
</para>

</directive>


<directive name="source_charset">
<syntax><value>charset</value></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if in location</context>

<para>
定义响应中的原始字符集。
如果这个字符集和<link id="charset"/>指令设置字符集的不同，就会进行转换。
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/en/docs/http/ngx_http_charset_module.xml
<?xml version="1.0"?>

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Module ngx_http_charset_module"
        link="/en/docs/http/ngx_http_charset_module.html"
        lang="en">

<section id="summary">

<para>
The <literal>ngx_http_charset_module</literal> module adds the specified
charset to the <header>Content-Type</header> response header field.
In addition, the module can convert data from one charset to another,
with some limitations:
<list type="bullet">

<listitem>
conversion is performed one way — from server to client,
</listitem>

<listitem>
only single-byte charsets can be converted
</listitem>

<listitem>
or single-byte charsets to/from UTF-8.
</listitem>

</list>
</para>

</section>


<section id="example" name="Example Configuration">

<para>
<example>
    include        conf/koi-win;

    charset        windows-1251;
    source_charset koi8-r;
</example>
</para>

</section>


<section id="directives" name="Directives">

<directive name="charset">
<syntax><value>charset</value> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if in location</context>

<para>
Adds the specified charset to the <header>Content-Type</header>
response header field.
If this charset is different from the charset specified
in the <link id="source_charset"/> directive, a conversion is performed.
</para>

<para>
The parameter <literal>off</literal> cancels the addition of charset
to the <header>Content-Type</header> response header field.
</para>

<para>
A charset can be defined with a variable:
<example>
charset $charset;
</example>
In such a case, all possible values of a variable need to be present
in the configuration at least once in the form of the
<link id="charset_map"/>, <link id="charset"/>, or
<link id="source_charset"/> directives.
For <literal>utf-8</literal>, <literal>windows-1251</literal>, and
<literal>koi8-r</literal> charsets it is sufficient to include the files
<path>conf/koi-win</path>, <path>conf/koi-utf</path>, and
<path>conf/win-utf</path> into configuration.
For other charsets, simply making a fictitious conversion table works,
for example:
<example>
charset_map iso-8859-5 _ { }
</example>
</para>

</directive>


<directive name="charset_map">
<syntax block="yes"><value>charset1</value> <value>charset2</value></syntax>
<default/>
<context>http</context>

<para>
Describes the conversion table from one charset to another.
A reverse conversion table is built using the same data.
Character codes are given in hexadecimal.
Missing characters in the range 80-FF are replaced with “<literal>?</literal>”.
When converting from UTF-8, characters missing in a one-byte charset
are replaced with “<literal>&amp;#XXXX;</literal>”.
</para>

<para>
Example:
<example>
charset_map koi8-r windows-1251 {
    C0 FE ; # small yu
    C1 E0 ; # small a
    C2 E1 ; # small b
    C3 F6 ; # small ts
    ...
}
</example>
</para>

<para>
When describing a conversion table to UTF-8, codes for the UTF-8 charset should
be given in the second column, for example:
<example>
charset_map koi8-r utf-8 {
    C0 D18E ; # small yu
    C1 D0B0 ; # small a
    C2 D0B1 ; # small b
    C3 D186 ; # small ts
    ...
}
</example>
</para>

<para>
Full conversion tables from <literal>koi8-r</literal> to
<literal>windows-1251</literal>, and from <literal>koi8-r</literal> and
<literal>windows-1251</literal> to <literal>utf-8</literal>
are provided in the distribution files <path>conf/koi-win</path>,
<path>conf/koi-utf</path>, and <path>conf/win-utf</path>.
</para>

</directive>


<directive name="charset_types">
<syntax><value>mime-type</value> ...</syntax>
<default>text/html text/xml text/plain text/vnd.wap.wml
application/x-javascript application/rss+xml</default>
<context>http</context>
<context>server</context>
<context>location</context>
<appeared-in>0.7.9</appeared-in>

<para>
Enables module processing in responses with the specified MIME types
in addition to “<literal>text/html</literal>”.
</para>

</directive>


<directive name="override_charset">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if in location</context>

<para>
Determines if a conversion should be performed for answers
received from a proxied or FastCGI server,
if the answers already carry a charset in the <header>Content-Type</header>
response header field.
If conversion is enabled, a charset specified in the received
response is used as a source charset.
<note>
It should be noted that if a response was received in a subrequest
then conversion from the response charset to the main request charset
is always performed regardless of the <literal>override_charset</literal>
directive setting.
</note>
</para>

</directive>


<directive name="source_charset">
<syntax><value>charset</value></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if in location</context>

<para>
Defines the source charset of a response.
If this charset is different from the charset specified
in the <link id="charset"/> directive, a conversion is performed.
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/http/ngx_http_rewrite_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="ngx_http_rewrite_module模块"
        link="/cn/docs/http/ngx_http_rewrite_module.html"
        lang="cn"
        translator="cfsego"
        rev="2">

<section id="summary">

<para>
<literal>ngx_http_rewrite_module</literal>模块允许正则替换URI，返回页面重定向，和按条件选择配置。
</para>

<para>
<literal>ngx_http_rewrite_module</literal>模块指令按以下顺序处理：
<list type="bullet">

<listitem>
处理在<link doc="ngx_http_core_module.xml" id="server"/>级别中定义的模块指令；
</listitem>

<listitem>
为请求查找location；
</listitem>

<listitem>
处理在选中的<link doc="ngx_http_core_module.xml" id="location"/>中定义的模块指令。如果指令改变了URI，按新的URI查找location。这个循环至多重复<link doc="ngx_http_core_module.xml" id="internal">10次</link>，之后nginx返回错误<http-status code="500" text="Internal Server Error"/>。
</listitem>

</list>
</para>

</section>


<section id="directives" name="指令">

<directive name="break">
<syntax/>
<default/>
<context>server</context>
<context>location</context>
<context>if</context>

<para>
停止处理当前这一轮的<literal>ngx_http_rewrite_module</literal>指令集。
</para>

<para>
举例：
<example>
if ($slow) {
    limit_rate 10k;
    break;
}
</example>
</para>

</directive>


<directive name="if">
<syntax block="yes">(<value>condition</value>)</syntax>
<default/>
<context>server</context>
<context>location</context>

<para>
计算指定的<value>condition</value>的值。如果为真，执行定义在大括号中的rewrite模块指令，并将<literal>if</literal>指令中的配置指定给请求。<literal>if</literal>指令会从上一层配置中继承配置。
</para>

<para>
条件可以是下列任意一种：
<list type="bullet">

<listitem>
变量名；如果变量值为空或者是以“<literal>0</literal>”开始的字符串，则条件为假；
</listitem>

<listitem>
使用“<literal>=</literal>”和“<literal>!=</literal>”运算符比较变量和字符串；
</listitem>

<listitem>
使用“<literal>~</literal>”（大小写敏感）和“<literal>~*</literal>”（大小写不敏感）运算符匹配变量和正则表达式。正则表达式可以包含匹配组，匹配结果后续可以使用变量<var>$1</var>..<var>$9</var>引用。如果正则表达式中包含字符“<literal>}</literal>”或者“<literal>;</literal>”，整个表达式应该被包含在单引号或双引号的引用中。
</listitem>

<listitem>
使用“<literal>-f</literal>”和“<literal>!-f</literal>”运算符检查文件是否存在；
</listitem>

<listitem>
使用“<literal>-d</literal>”和“<literal>!-d</literal>”运算符检查目录是否存在；
checking a directory existence with the “<literal>-d</literal>” and
</listitem>

<listitem>
使用“<literal>-e</literal>”和“<literal>!-e</literal>”运算符检查文件、目录或符号链接是否存在；
</listitem>

<listitem>
使用“<literal>-x</literal>”和“<literal>!-x</literal>”运算符检查可执行文件；
</listitem>

</list>
</para>

<para>
举例：
<example>
if ($http_user_agent ~ MSIE) {
    rewrite ^(.*)$ /msie/$1 break;
}

if ($http_cookie ~* "id=([^;]+)(?:;|$)") {
    set $id $1;
}

if ($request_method = POST) {
    return 405;
}

if ($slow) {
    limit_rate 10k;
}

if ($invalid_referer) {
    return 403;
}
</example>
<note>
内嵌变量<var>$invalid_referer</var>的值是通过<link doc="ngx_http_referer_module.xml" id="valid_referers"/>指令设置的。
</note>
</para>

</directive>


<directive name="return">
<syntax><value>code</value> [<value>text</value>]</syntax>
<syntax><value>code</value> <value>URL</value></syntax>
<syntax><value>URL</value></syntax>
<default/>
<context>server</context>
<context>location</context>
<context>if</context>

<para>
停止处理并返回指定<value>code</value>给客户端。返回非标准的状态码444可以直接关闭连接而不返回响应头。
</para>

<para>
从0.8.42版开始，可以在指令中指定重定向的URL（状态码为301、302、303和307），或者指定响应体<value>文本</value>（状态码为其它值）。响应体文本或重定向URL中可以包含变量。作为一种特殊情况，重定向URL可以简化为当前server的本地URI，那么完整的重定向URL将按照请求协议（<var>$scheme</var>）、<link doc="ngx_http_core_module.xml" id="server_name_in_redirect"/>指令和<link doc="ngx_http_core_module.xml" id="port_in_redirect"/>指令的配置进行补全。
</para>

<para>
另外，状态码为302的临时重定向使用的<value>URL</value>可以作为指令的唯一参数。该参数应该以“<literal>http://</literal>”、“<literal>https://</literal>”或者“<literal>https://</literal>”开始。<value>URL</value>中可以包含变量。
</para>

<para>
<note>
0.7.51版本以前只能返回下面状态码：
204、400、402 — 406、408、410、411、413、416 和 500 — 504。
</note>

<note>
直到1.1.16和1.0.13版，状态码307才被认为是一种重定向。
</note>
</para>

</directive>


<directive name="rewrite">
<syntax>
    <value>regex</value>
    <value>replacement</value>
    [<value>flag</value>]</syntax>
<default/>
<context>server</context>
<context>location</context>
<context>if</context>

<para>
如果指定的正则表达式能匹配URI，此URI将被<value>replacement</value>参数定义的字符串改写。<literal>rewrite</literal>指令按其在配置文件中出现的顺序执行。flag可以终止后续指令的执行。如果replacement的字符串以“<literal>http://</literal>”或“<literal>https://</literal>”开头，nginx将结束执行过程，并返回给客户端一个重定向。
</para>

<para>
可选的<value>flag</value>参数可以是其中之一：
<list type="tag">

<tag-name><literal>last</literal></tag-name>
<tag-desc>
停止执行当前这一轮的<literal>ngx_http_rewrite_module</literal>指令集，然后查找匹配改变后URI的新location；
</tag-desc>

<tag-name><literal>break</literal></tag-name>
<tag-desc>
停止执行当前这一轮的<literal>ngx_http_rewrite_module</literal>指令集；
</tag-desc>

<tag-name><literal>redirect</literal></tag-name>
<tag-desc>
在replacement字符串未以“<literal>http://</literal>”或“<literal>https://</literal>”开头时，使用返回状态码为302的临时重定向；
</tag-desc>

<tag-name><literal>permanent</literal></tag-name>
<tag-desc>
返回状态码为301的永久重定向。
</tag-desc>

</list>
完整的重定向URL将按照请求协议（<var>$scheme</var>）、<link doc="ngx_http_core_module.xml" id="server_name_in_redirect"/>指令和<link doc="ngx_http_core_module.xml" id="port_in_redirect"/>指令的配置进行补全。
</para>

<para>
举例：
<example>
server {
    ...
    rewrite ^(/download/.*)/media/(.*)\..*$ $1/mp3/$2.mp3 last;
    rewrite ^(/download/.*)/audio/(.*)\..*$ $1/mp3/$2.ra  last;
    return  403;
    ...
}
</example>
</para>

<para>
但是当上述指令写在“<literal>/download/</literal>”的location中时，应使用标志<literal>break</literal>代替<literal>last</literal>，否则nginx会重复10轮循环，然后返回错误500：
<example>
location /download/ {
    rewrite ^(/download/.*)/media/(.*)\..*$ $1/mp3/$2.mp3 break;
    rewrite ^(/download/.*)/audio/(.*)\..*$ $1/mp3/$2.ra  break;
    return  403;
}
</example>
</para>

<para>
如果<value>replacement</value>字符串包括新的请求参数，以往的请求参数会添加到新参数后面。如果不希望这样，在replacement字符串末尾加一个问号“？”，就可以避免，比如：
<example>
rewrite ^/users/(.*)$ /show?user=$1? last;
</example>
</para>

<para>
如果正则表达式中包含字符“<literal>}</literal>”或者“<literal>;</literal>”，整个表达式应该被包含在单引号或双引号的引用中。
</para>

</directive>


<directive name="rewrite_log">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if</context>

<para>
开启或者关闭将<literal>ngx_http_rewrite_module</literal>模块指令的处理日志以<literal>notice</literal>级别记录到错误日志中。
</para>

</directive>


<directive name="set">
<syntax><value>variable</value> <value>value</value></syntax>
<default/>
<context>server</context>
<context>location</context>
<context>if</context>

<para>
为指定变量<value>variable</value>设置变量值<value>value</value>。<value>value</value>可以包含文本、变量或者它们的组合。
</para>

</directive>


<directive name="uninitialized_variable_warn">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>on</default>
<context>http</context>
<context>server</context>
<context>location</context>
<context>if</context>

<para>
控制是否记录变量未初始化的警告到日志。
</para>

</directive>

</section>


<section id="internals" name="内部实现">

<para>
<literal>ngx_http_rewrite_module</literal>模块的指令在解析配置阶段被编译成nginx内部指令。这些内部指令在处理请求时被解释执行。而解释器是一个简单的堆栈机器。
</para>

<para>
比如，下面指令
<example>
location /download/ {
    if ($forbidden) {
        return 403;
    }

    if ($slow) {
        limit_rate 10k;
    }

    rewrite ^/(download/.*)/media/(.*)\..*$ /$1/mp3/$2.mp3 break;
}
</example>
将被翻译成下面这些指令：
<example>
variable $forbidden
check against zero
    return 403
    end of code
variable $slow
check against zero
match of regular expression
copy "/"
copy $1
copy "/mp3/"
copy $2
copy ".mp3"
end of regular expression
end of code
</example>
</para>

<para>
请注意没有对应上面的<link doc="ngx_http_core_module.xml" id="limit_rate"/>指令的内部指令，因为这个指令与<literal>ngx_http_rewrite_module</literal>模块无关。nginx会为这个<link id="if"/>块单独创建一个配置，包含<literal>limit_rate</literal>等于10k。如果条件为真，nginx将把这个配置指派给请求。
</para>

<para>
指令
<example>
rewrite ^/(download/.*)/media/(.*)\..*$ /$1/mp3/$2.mp3 break;
</example>
可以通过将正则表达式中的第一个斜线“/”放入圆括号，来实现节约一个内部指令：
<example>
rewrite ^(<emphasis>/</emphasis>download/.*)/media/(.*)\..*$ $1/mp3/$2.mp3 break;
</example>
对应的内部指令将会是这样：
<example>
match of regular expression
copy $1
copy "/mp3/"
copy $2
copy ".mp3"
end of regular expression
end of code
</example>
</para>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/http/ngx_http_access_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="ngx_http_access_module模块"
        link="/cn/docs/http/ngx_http_access_module.html"
        lang="cn"
        translator="WenMing"
        rev="1">

<section id="summary">

<para>
模块 <literal>ngx_http_access_module</literal> 允许限制某些IP地址的客户端访问。
</para>

<para>
也可以通过
<link doc="ngx_http_auth_basic_module.xml">密码</link>来限制访问。
使用
 <link doc="ngx_http_core_module.xml" id="satisfy"/> 指令就能同时通过IP地址和密码来限制访问。
</para>

</section>


<section id="example" name="配置范例">

<para>
<example>
location / {
    deny  192.168.1.1;
    allow 192.168.1.0/24;
    allow 10.1.1.0/16;
    allow 2001:0db8::/32;
    deny  all;
}
</example>
</para>

<para>
规则按照顺序依次检测，直到匹配到第一条规则。
在这个例子里，IPv4的网络中只有
<literal>10.1.1.0/16</literal> 和 <literal>192.168.1.0/24</literal>允许访问，但
<literal>192.168.1.1</literal>除外,
对于IPv6的网络，只有<literal>2001:0db8::/32</literal>允许访问。
在规则很多的情况下，使用
<link doc="ngx_http_geo_module.xml">ngx_http_geo_module</link>
模块变量更合适。
</para>

</section>


<section id="directives" name="指令">

<directive name="allow">
<syntax>
    <value>address</value> |
    <value>CIDR</value> |
    <literal>all</literal></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>
<context>limit_except</context>

<para>
允许指定的网络地址访问。
</para>

</directive>


<directive name="deny">
<syntax>
    <value>address</value> |
    <value>CIDR</value> |
    <literal>all</literal></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>
<context>limit_except</context>

<para>
拒绝指定的网络地址访问。
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/http/ngx_http_gunzip_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Maxim Dounin
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="ngx_http_gunzip_module模块"
        link="/cn/docs/http/ngx_http_gunzip_module.html"
        lang="cn"
        translator="nigelzeng"
        rev="1">

<section id="summary">

<para>
<literal>ngx_http_gunzip_module</literal>模块是一个过滤器，
它为不支持“gzip”编码方法的客户端解压具有“<literal>Content-Encoding: gzip</literal>”头的响应。
当希望存储压缩后的数据以节省空间和减少I/O开销，又不希望对那些不支持gzip压缩的客户端造成不利影响时，
此模块会派上用途。
</para>

<para>
这个模块默认不会安装，需要使用<literal>--with-http_gunzip_module</literal>配置参数来启用。
</para>

</section>


<section id="example" name="配置实例">

<para>
<example>
location /storage/ {
    gunzip on;
    ...
}
</example>
</para>

</section>


<section id="directives" name="指令">

<directive name="gunzip">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
针对缺少gzip支持的客户端，启用或者禁用解压经过gzip压缩的响应。
如果启用，也需要考虑以下指令以确定客户端是否支持gzip：
<link doc="ngx_http_gzip_module.xml" id="gzip_http_version">gzip_http_version</link>，
<link doc="ngx_http_gzip_module.xml" id="gzip_proxied">gzip_proxied</link>，
和<link doc="ngx_http_gzip_module.xml" id="gzip_disable">gzip_disable</link>，
另请参阅<link doc="ngx_http_gzip_module.xml" id="gzip_vary">gzip_vary</link>指令。
</para>

</directive>


<directive name="gunzip_buffers">
<syntax><value>number</value> <value>size</value></syntax>
<default>32 4k|16 8k</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
设置用于解压一个响应的缓存数和大小。默认的缓存大小等于一个内存页大小。
该值为4K或者8K，取决于具体系统平台。
</para>

</directive>

</section>

</module>
