=== taobao/nginx-docs-cn/dtd/module.dtd
<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->


<!ELEMENT   module      (section+) >
<!ATTLIST   module
            name        CDATA #REQUIRED
            link        CDATA #REQUIRED
            lang        CDATA #REQUIRED
            rev         CDATA #IMPLIED
            translator  CDATA #IMPLIED
            toc         (yes | no) "yes"
>

<!ELEMENT   section     (directive | para)+ >
<!ATTLIST   section
            id          ID #REQUIRED
            name        CDATA #IMPLIED
>

<!ELEMENT   directive   (syntax+, default+, context+, appeared-in*, para+) >
<!ATTLIST   directive
            name        ID #REQUIRED
>

<!ELEMENT   syntax      (#PCDATA | literal | value)* >
<!ATTLIST   syntax
            block       (yes | no) "no"
>

<!ELEMENT   default     (#PCDATA)* >

<!ELEMENT   context     (#PCDATA)* >

<!ELEMENT   appeared-in (#PCDATA)* >

<!ELEMENT   para        (#PCDATA | c-def | c-func | command |
                         emphasis | example | header | http-status | link |
                         list | literal | note | path | value | var)* >

<!ELEMENT   c-def       (#PCDATA)* >

<!ELEMENT   c-func      (#PCDATA)* >

<!ELEMENT   command     (#PCDATA)* >

<!ELEMENT   emphasis    (#PCDATA | value)* >

<!ELEMENT   example     (#PCDATA | value | emphasis)* >

<!ELEMENT   header      (#PCDATA | value)* >

<!ELEMENT   http-status EMPTY >
<!ATTLIST   http-status
            code        CDATA #REQUIRED
            text        CDATA #IMPLIED
>

<!ELEMENT   link        (#PCDATA)* >
<!ATTLIST   link
            doc         CDATA #IMPLIED
            id          CDATA #IMPLIED
            url         CDATA #IMPLIED
>

<!ELEMENT   list        (listitem+ | (tag-name | tag-desc)+) >
<!ATTLIST   list
            type        (bullet | enum | tag) #REQUIRED
            compact     (yes | no) "yes"
>

<!ELEMENT   listitem    ANY >
<!ATTLIST   listitem
            id          ID #IMPLIED
>

<!ELEMENT   tag-name    ANY >
<!ATTLIST   tag-name
            id          ID #IMPLIED
>

<!ELEMENT   tag-desc    ANY >

<!ELEMENT   literal     (#PCDATA | value)* >

<!ELEMENT   note        ANY >

<!ELEMENT   path        (#PCDATA)* >

<!ELEMENT   value       (#PCDATA)* >

<!ELEMENT   var         (#PCDATA)* >

<!ENTITY    nbsp        "&#xA0;" >
<!ENTITY    mdash       "&nbsp;- " >

=== taobao/nginx-docs-cn/xml/ru/docs/mail/ngx_mail_ssl_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) 2006, 2007 Anton Yuzhaninov
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Модуль ngx_mail_ssl_module"
        link="/ru/docs/mail/ngx_mail_ssl_module.html"
        lang="ru"
        rev="2">

<section id="summary">

<para>
Модуль <literal>ngx_mail_ssl_module</literal> обеспечивает работу
почтового прокси-сервера по протоколу SSL/TLS.
</para>

<para>
По умолчанию этот модуль не собирается, его сборку необходимо
разрешить с помощью конфигурационного параметра
<literal>--with-mail_ssl_module</literal>.
<note>
Для сборки и работы этого модуля нужна библиотека
<link url="http://www.openssl.org">OpenSSL</link>.
</note>
</para>

</section>


<section id="directives" name="Директивы">

<directive name="ssl">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>off</default>
<context>mail</context>
<context>server</context>

<para>
Включает протокол SSL/TLS для данного сервера.
</para>

</directive>


<directive name="ssl_certificate">
<syntax><value>файл</value></syntax>
<default/>
<context>mail</context>
<context>server</context>

<para>
Указывает файл с сертификатом в формате PEM
для данного сервера.
Если вместе с основным сертификатом нужно указать промежуточные,
то они должны находиться в этом же файле в следующем порядке — сначала
основной сертификат, а затем промежуточные.
В этом же файле может находиться секретный ключ в формате PEM.
</para>

</directive>


<directive name="ssl_certificate_key">
<syntax><value>файл</value></syntax>
<default/>
<context>mail</context>
<context>server</context>

<para>
Указывает файл с секретным ключом в формате PEM
для данного сервера.
</para>

</directive>


<directive name="ssl_prefer_server_ciphers">
<syntax><literal>on</literal> | <literal>off</literal></syntax>
<default>off</default>
<context>mail</context>
<context>server</context>

<para>
Указывает, чтобы при использовании протоколов SSLv3 и TLS
серверные шифры были более приоритетны, чем клиентские.
</para>

</directive>


<directive name="ssl_protocols">
<syntax>
    [<literal>SSLv2</literal>]
    [<literal>SSLv3</literal>]
    [<literal>TLSv1</literal>]
    [<literal>TLSv1.1</literal>]
    [<literal>TLSv1.2</literal>]</syntax>
<default>SSLv3 TLSv1 TLSv1.1 TLSv1.2</default>
<context>mail</context>
<context>server</context>

<para>
Разрешает указанные протоколы.
Параметры <literal>TLSv1.1</literal> и <literal>TLSv1.2</literal> работают
только при использовании библиотеки OpenSSL версии 1.0.1 и выше.
<note>
Параметры <literal>TLSv1.1</literal> и <literal>TLSv1.2</literal> поддерживаются
только начиная с версий 1.1.13 и 1.0.12,
поэтому при использовании OpenSSL версии 1.0.1
и выше на старых версиях nginx эти протоколы работать будут, однако их нельзя
будет отключить.
</note>
</para>

</directive>


<directive name="ssl_session_cache">
<syntax>
    <literal>off</literal> |
    <literal>none</literal> |
    [<literal>builtin</literal>[:<value>размер</value>]]
    [<literal>shared</literal>:<value>название</value>:<value>размер</value>]</syntax>
<default>none</default>
<context>mail</context>
<context>server</context>

<para>
Задаёт тип и размеры кэшей для хранения параметров сессий.
Тип кэша может быть следующим:
<list type="tag" compact="no">

<tag-name><literal>off</literal></tag-name>
<tag-desc>
жёсткое запрещение использования кэша сессий:
nginx явно говорит клиенту, что сессии не могут использоваться повторно.
</tag-desc>

<tag-name><literal>none</literal></tag-name>
<tag-desc>
мягкое запрещение использования кэша сессий:
nginx говорит клиенту, что сессии могут использоваться повторно, но
на самом деле не используются.
</tag-desc>

<tag-name><literal>builtin</literal></tag-name>
<tag-desc>
встроенный в OpenSSL кэш, используется в рамках только одного рабочего процесса.
Размер кэша задаётся в сессиях.
Если размер не задан, то он равен 20480 сессиям.
Использование встроенного кэша может вести к фрагментации памяти.
</tag-desc>

<tag-name><literal>shared</literal></tag-name>
<tag-desc>
разделяемый между всеми рабочими процессами.
Размер кэша задаётся в байтах, в 1 мегабайт может поместиться
около 4000 сессий.
У каждого разделяемого кэша должно быть произвольное название.
Кэш с одинаковым названием может использоваться в нескольких
серверах.
</tag-desc>

</list>
</para>

<para>
Можно использовать одновременно оба типа кэша, например:
<example>
ssl_session_cache builtin:1000 shared:SSL:10m;
</example>
однако использование только разделяемого кэша без встроенного должно
быть более эффективным.
</para>

</directive>


<directive name="ssl_session_timeout">
<syntax><value>время</value></syntax>
<default>5m</default>
<context>mail</context>
<context>server</context>

<para>
Задаёт время, в течение которого клиент может повторно
использовать параметры сессии, хранящейся в кэше.
</para>

</directive>


<directive name="starttls">
<syntax>
  <literal>on</literal> |
  <literal>off</literal> |
  <literal>only</literal></syntax>
<default>off</default>
<context>mail</context>
<context>server</context>

<para>
<list type="tag">

<tag-name><literal>on</literal></tag-name>
<tag-desc>
разрешить использование команд <literal>STLS</literal> для POP3
и <literal>STARTTLS</literal> для IMAP;
</tag-desc>

<tag-name><literal>off</literal></tag-name>
<tag-desc>
запретить использование команд <literal>STLS</literal>
и <literal>STARTTLS</literal>;
</tag-desc>

<tag-name><literal>only</literal></tag-name>
<tag-desc>
требовать предварительного перехода на TLS.
</tag-desc>

</list>
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/ru/docs/http/ngx_http_split_clients_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Модуль ngx_http_split_clients_module"
        link="/ru/docs/http/ngx_http_split_clients_module.html"
        lang="ru"
        rev="2">

<section id="summary">

<para>
Модуль <literal>ngx_http_split_clients_module</literal> создаёт переменные для
A/B тестирования (также известного как “split-тестирование”).
</para>

</section>


<section id="example" name="Пример конфигурации">

<para>
<example>
http {
    split_clients "${remote_addr}AAA" $variant {
                   0.5%               .one;
                   2.0%               .two;
                   *                  "";
    }

    server {
        location / {
            index index${variant}.html;
</example>
</para>

</section>


<section id="directives" name="Директивы">

<directive name="split_clients">
<syntax block="yes">
    <value>строка</value>
    <value>$переменная</value></syntax>
<default/>
<context>http</context>

<para>
Создаёт переменную для A/B тестирования, например:
<example>
split_clients "${remote_addr}AAA" $variant {
               0.5%               .one;
               2.0%               .two;
               *                  "";
}
</example>
Значение исходной строки хэшируется с помощью MurmurHash2.
В приведённом примере при значениях хэша от 0 до 21474835 (0.5%)
переменная <var>$variant</var> получит значение <literal>".one"</literal>.
При значениях хэша от 21474836 до 107374180 (2%) — <literal>".two"</literal>.
И при значениях хэша от 107374181 до 4294967295 — <literal>""</literal>
(пустая строка).
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/ru/docs/mail/ngx_mail_auth_http_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) 2006, 2007 Anton Yuzhaninov
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Модуль ngx_mail_auth_http_module"
        link="/ru/docs/mail/ngx_mail_auth_http_module.html"
        lang="ru"
        rev="1">

<section id="directives" name="Директивы">

<directive name="auth_http">
<syntax><value>URL</value></syntax>
<default/>
<context>mail</context>
<context>server</context>

<para>
Задаёт URL HTTP-сервера авторизации.
Протокол описан ниже.
</para>

</directive>


<directive name="auth_http_header">
<syntax><value>заголовок</value> <value>значение</value></syntax>
<default/>
<context>mail</context>
<context>server</context>

<para>
Позволяет добавить указанный заголовок к запросам на сервер авторизации.
Можно использовать в качестве shared secret для проверки,
что запрос поступил от nginx.
Например:
<example>
auth_http_header X-Auth-Key "secret_string";
</example>
</para>

</directive>


<directive name="auth_http_timeout">
<syntax><value>время</value></syntax>
<default>60s</default>
<context>mail</context>
<context>server</context>

<para>
</para>

</directive>

</section>


<section id="protocol" name="Протокол">

<para>
Для общения с сервером авторизации используется HTTP.
Данные в теле ответа игнорируются, информация передаётся только в заголовках.
</para>

<para>
Примеры запросов и ответов:
</para>

<para>
Запрос:
<example>
GET /auth HTTP/1.0
Host: localhost
Auth-Method: plain # plain или apop или cram-md5
Auth-User: user
Auth-Pass: password
Auth-Protocol: imap # imap, pop3 или smtp
Auth-Login-Attempt: 1 # какая по счёту попытка в рамках одной сессии
Client-IP: 192.168.1.1
</example>
Хороший ответ:
<example>
HTTP/1.0 200 OK # эта строка игнорируется
Auth-Status: OK
Auth-Server: 10.1.1.1
Auth-Port: 143
</example>
Плохой ответ:
<example>
HTTP/1.0 200 OK # эта строка игнорируется
Auth-Status: Invalid login or password
Auth-Wait: 3 # подождать три секунды перед выдачей ошибки клиенту
</example>
</para>

<para>
Если заголовка <header>Auth-Wait</header> нет,
то после выдачи ошибки соединение будет закрыто.
В текущей реализации на каждую попытку авторизации выделяется память,
которая освобождается только при завершении сессии.
Поэтому число неудачных попыток авторизации в рамках одной сессии
должно быть ограничено — после 10-20 попыток (см. заголовок
<header>Auth-Login-Attempt</header>) сервер должен выдать ответ
без заголовка <header>Auth-Wait</header>.
</para>

<para>
При использовании APOP или CRAM-MD5 запрос-ответ будут выглядеть так:
<example>
GET /auth HTTP/1.0
Host: localhost
Auth-Method: apop
Auth-User: user
Auth-Salt: &lt;238188073.1163692009@mail.example.com&gt;
Auth-Pass: auth_response
Auth-Protocol: imap
Auth-Login-Attempt: 1 # какая по счёту попытка в рамках одной сессии
Client-IP: 192.168.1.1
</example>
Хороший ответ:
<example>
HTTP/1.0 200 OK # эта строка игнорируется
Auth-Status: OK
Auth-Server: 10.1.1.1
Auth-Port: 143
Auth-Pass: plain-text-pass
</example>
</para>

<para>
Для SMTP в ответе дополнительно учитывается заголовок
<header>Auth-Error-Code</header> — если он есть,
то используется как код ответа в случае ошибки.
Если нет, то по умолчанию к <header>Auth-Status</header>
будет добавлен код 535 5.7.0.
</para>

<para>
Например, если от сервера авторизации будет получен ответ:
<example>
HTTP/1.0 200 OK
Auth-Status: Temporary server problem, try again later
Auth-Error-Code: 451 4.3.0
Auth-Wait: 3
</example>
то по SMTP клиенту будет выдана ошибка
<example>
451 4.3.0 Temporary server problem, try again later
</example>
</para>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/http/ngx_http_referer_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="ngx_http_referer_module模块"
        link="/cn/docs/http/ngx_http_referer_module.html"
        lang="cn"
        translator="nigelzeng"
        rev="1">

<section id="summary">

<para>
<literal>ngx_http_referer_module</literal>模块允许拦截<header>Referer</header>请求头中含有非法值的请求，阻止它们访问站点。
需要注意的是伪造一个有效的<header>Referer</header>请求头是相当容易的，
因此这个模块的预期目的不在于彻底地阻止这些非法请求，而是为了阻止由正常浏览器发出的大规模此类请求。
还有一点需要注意，即使正常浏览器发送的合法请求，也可能没有<header>Referer</header>请求头。
</para>

</section>


<section id="example" name="配置实例">

<para>
<example>
valid_referers none blocked server_names
               *.example.com example.* www.example.org/galleries/
               ~\.google\.;

if ($invalid_referer) {
    return 403;
}
</example>
</para>

</section>


<section id="directives" name="指令">

<directive name="referer_hash_bucket_size">
<syntax><value>size</value></syntax>
<default>64</default>
<context>server</context>
<context>location</context>
<appeared-in>1.0.5</appeared-in>

<para>
设置用来存储有效referer的哈希桶的大小。
详细的情况参见<link doc="../hash.xml">哈希表设置</link>。
</para>

</directive>


<directive name="referer_hash_max_size">
<syntax><value>size</value></syntax>
<default>2048</default>
<context>server</context>
<context>location</context>
<appeared-in>1.0.5</appeared-in>

<para>
设置用来存储有效referer的哈希表最大<value>容量</value>。
详细的情况参见<link doc="../hash.xml">哈希表设置</link>。
</para>

</directive>


<directive name="valid_referers">
<syntax>
    <literal>none</literal> |
    <literal>blocked</literal> |
    <literal>server_names</literal> |
    <value>string</value>
    ...</syntax>
<default/>
<context>server</context>
<context>location</context>

<para>
<header>Referer</header>请求头为指定值时，内嵌变量<var>$invalid_referer</var>被设置为空字符串，
否则这个变量会被置成“<literal>1</literal>”。查找匹配时不区分大小写。
</para>

<para>
该指令的参数可以为下面的内容：
<list type="tag">

<tag-name><literal>none</literal></tag-name>
<tag-desc>
缺少<header>Referer</header>请求头；
</tag-desc>

<tag-name><literal>blocked</literal></tag-name>
<tag-desc>
<header>Referer</header> 请求头存在，但是它的值被防火墙或者代理服务器删除；
这些值都不以“<literal>http://</literal>” 或者 “<literal>https://</literal>”字符串作为开头；
</tag-desc>

<tag-name><literal>server_names</literal></tag-name>
<tag-desc>
<header>Referer</header> 请求头包含某个虚拟主机名；
</tag-desc>

<tag-name>任意字符串</tag-name>
<tag-desc>
定义一个服务器名和可选的URI前缀。服务器名允许在开头或结尾使用“<literal>*</literal>”符号。
当nginx检查时，<header>Referer</header>请求头里的服务器端口将被忽略。
</tag-desc>

<tag-name>正则表达式</tag-name>
<tag-desc>
必须以“<literal>~</literal>”符号作为开头。
需要注意的是表达式会从“<literal>http://</literal>”或者“<literal>https://</literal>”之后的文本开始匹配。
</tag-desc>

</list>
</para>

<para>
实例:
<example>
valid_referers none blocked server_names
               *.example.com example.* www.example.org/galleries/
               ~\.google\.;
</example>
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/http/ngx_http_memcached_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Module ngx_http_memcached_module"
        link="/cn/docs/http/ngx_http_memcached_module.html"
        lang="cn"
        translator="allisstone"
        rev="2">

<section id="summary">

<para>
<literal>ngx_http_memcached_module</literal> 模块允许从一个memcached服务器获取响应。
键在变量<var>$memcached_key</var> 中来设置。响应应经由nginx的外部方法提前放入memcached。
</para>

</section>


<section id="example" name="Example Configuration">

<para>
<example>
server {
    location / {
        set            $memcached_key "$uri?$args";
        memcached_pass host:11211;
        error_page     404 502 504 = @fallback;
    }

    location @fallback {
        proxy_pass     http://backend;
    }
}
</example>
</para>

</section>


<section id="directives" name="Directives">

<directive name="memcached_buffer_size">
<syntax><value>size</value></syntax>
<default>4k|8k</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
设置用来接收memcached服务器的响应的读缓存
 <value>size</value> 大小。
响应一经收到，就立刻同步传送给客户端。
</para>

</directive>


<directive name="memcached_connect_timeout">
<syntax><value>time</value></syntax>
<default>60s</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
设置一个与memcached服务器建立连接的超时时间。
应当注意的是这个超时时间一般不能超过75秒。
</para>

</directive>


<directive name="memcached_gzip_flag">
<syntax><value>flag</value></syntax>
<default></default>
<context>http</context>
<context>server</context>
<context>location</context>
<appeared-in>1.3.6</appeared-in>

<para>
开启测试memcatched服务器响应是否出现<value>flag</value>标志，
并且标志出现时，设置
“<literal>Content-Encoding</literal>” 响应头为 “<literal>gzip</literal>”。
</para>

</directive>


<directive name="memcached_next_upstream">
<syntax>
    <literal>error</literal> |
    <literal>timeout</literal> |
    <literal>invalid_response</literal> |
    <literal>not_found</literal> |
    <literal>off</literal>
    ...</syntax>
<default>error timeout</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
指定在何种情况下，请求应当传送给下一个服务器。
<list type="tag">

<tag-name><literal>error</literal></tag-name>
<tag-desc>在建立连接、发送请求或者读取响应头时出现了错误；</tag-desc>

<tag-name><literal>timeout</literal></tag-name>
<tag-desc>在建立连接、发送请求或者读取响应头时出现了超时；</tag-desc>

<tag-name><literal>invalid_response</literal></tag-name>
<tag-desc>服务器返回一个空的或者无效的响应；</tag-desc>

<tag-name><literal>not_found</literal></tag-name>
<tag-desc>服务器返回内容不存在响应；</tag-desc>

<tag-name><literal>off</literal></tag-name>
<tag-desc>禁止将请求传递给下一个服务器。</tag-desc>

</list>
</para>

<para>
应当认识到，仅当nginx还没有发送任何响应数据到客户端的时候，才能将请求传送给下一个服务器。
就是说，传输响应期间发生错误或者超时，问题不可修复。
</para>

</directive>


<directive name="memcached_pass">
<syntax><value>address</value></syntax>
<default/>
<context>location</context>
<context>if in location</context>

<para>
设置memcached服务器的地址。
地址可以指定为一个域名，也可以是地址和端口的组合，例如：
<example>
memcached_pass localhost:11211;
</example>
</para>

<para>
如果域名解析后对应多个地址，那么采用round-robin的方法来选择地址。
除此之外，服务器也可以被指定为
<link doc="ngx_http_upstream_module.xml">服务器组</link>.
</para>

</directive>


<directive name="memcached_read_timeout">
<syntax><value>time</value></syntax>
<default>60s</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
定义从memcached服务器读取响应的超时时间。
这不是整个响应传输时间的超时，而只是两次读操作之间的超时。
如果memcached服务器在此期间不传输任何数据，那么连接将会关闭。
</para>

</directive>


<directive name="memcached_send_timeout">
<syntax><value>time</value></syntax>
<default>60s</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
为传输一个请求到memcached服务器设置一个超时时间。
这不是整个请求传输时间的超时，而只是两次写操作之间的超时。
如果memcached服务器在此期间不传输任何数据，那么连接将会关闭。
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/ru/docs/http/ngx_http_browser_module.xml
<?xml version="1.0"?>

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Модуль ngx_http_browser_module"
        link="/ru/docs/http/ngx_http_browser_module.html"
        lang="ru">

<section id="summary">

<para>
Модуль <literal>ngx_http_browser_module</literal> создаёт переменные,
значения которых зависят от значения поля <header>User-Agent</header>
в заголовке запроса:
<list type="tag">

<tag-name><var>$modern_browser</var></tag-name>
<tag-desc>
равна значению, заданному директивой <link id="modern_browser_value"/>,
если браузер опознан как современный;
</tag-desc>

<tag-name><var>$ancient_browser</var></tag-name>
<tag-desc>
равна значению, заданному директивой <link id="ancient_browser_value"/>,
если браузер опознан как устаревший;
</tag-desc>

<tag-name><var>$msie</var></tag-name>
<tag-desc>
равна “1”, если браузер опознан как MSIE любой версии.
</tag-desc>

</list>
</para>

</section>


<section id="example" name="Пример конфигурации">

<para>
Выбор индексного файла:
<example>
    modern_browser_value "modern.";

    modern_browser msie      5.5;
    modern_browser gecko     1.0.0;
    modern_browser opera     9.0;
    modern_browser safari    413;
    modern_browser konqueror 3.0;

    index index.${modern_browser}html index.html;
</example>
</para>

<para>
Перенаправление для старых браузеров:
<example>
    modern_browser msie      5.0;
    modern_browser gecko     0.9.1;
    modern_browser opera     8.0;
    modern_browser safari    413;
    modern_browser konqueror 3.0;

    modern_browser unlisted;

    ancient_browser Links Lynx netscape4;

    if ($ancient_browser) {
        rewrite ^ /ancient.html;
    }
</example>
</para>

</section>


<section id="directives" name="Директивы">

<directive name="ancient_browser">
<syntax><value>строка</value> ...</syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Задаёт подстроки, при нахождении которых в поле <header>User-Agent</header>
заголовка запроса браузер считается устаревшим.
Специальная строка “<literal>netscape4</literal>” соответствует
регулярному выражению “<literal>^Mozilla/[1-4]</literal>”.
</para>

</directive>


<directive name="ancient_browser_value">
<syntax><value>строка</value></syntax>
<default>1</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Задаёт значение для переменных <var>$ancient_browser</var>.
</para>

</directive>


<directive name="modern_browser">
<syntax><value>браузер</value> <value>версия</value></syntax>
<syntax><literal>unlisted</literal></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Задаёт версию браузера, начиная с которой он считается современным.
В качестве браузера можно задать <literal>msie</literal>,
<literal>gecko</literal> (браузеры, созданные на основе Mozilla),
<literal>opera</literal>, <literal>safari</literal>
или <literal>konqueror</literal>.
</para>

<para>
Версии можно задать в форматах X, X.X, X.X.X или X.X.X.X.
Максимальные значения для каждого из форматов соответственно —
4000, 4000.99, 4000.99.99 и 4000.99.99.99.
</para>

<para>
Специальное значение <literal>unlisted</literal> указывает считать
современным браузер, не описанный директивами <literal>modern_browser</literal>
и <link id="ancient_browser"/>.
В противном случае неперечисленный браузер будет считаться устаревшим.
Если в заголовке запроса нет поля <header>User-Agent</header>, то браузер
считается неперечисленным.
</para>

</directive>


<directive name="modern_browser_value">
<syntax><value>строка</value></syntax>
<default>1</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Задаёт значение для переменных <var>$modern_browser</var>.
</para>

</directive>

</section>

</module>

=== taobao/nginx-docs-cn/xml/cn/docs/http/ngx_http_userid_module.xml
<?xml version="1.0"?>

<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE module SYSTEM "../../../../dtd/module.dtd">

<module name="Module ngx_http_userid_module"
        link="/en/docs/http/ngx_http_userid_module.html"
        lang="en"
        rev="1">

<section id="summary">

<para>
The <literal>ngx_http_userid_module</literal> module sets cookies
suitable for client identification.
Received and set cookies can be logged using the embedded variables
<var>$uid_got</var> and <var>$uid_set</var>.
This module is compatible with the
<link url="http://www.lexa.ru/programs/mod-uid-eng.html">mod_uid</link>
module for Apache.
</para>

</section>


<section id="example" name="Example Configuration">

<para>
<example>
userid         on;
userid_name    uid;
userid_domain  example.com;
userid_path    /;
userid_expires 365d;
userid_p3p     'policyref="/w3c/p3p.xml", CP="CUR ADM OUR NOR STA NID"';
</example>
</para>

</section>


<section id="directives" name="Directives">

<directive name="userid">
<syntax>
    <literal>on</literal> |
    <literal>v1</literal> |
    <literal>log</literal> |
    <literal>off</literal></syntax>
<default>off</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Allows or prohibits to set cookies and log the received cookies:
<list type="tag">

<tag-name><literal>on</literal></tag-name>
<tag-desc>
allows to set version 2 cookies
and log the received cookies;
</tag-desc>

<tag-name><literal>v1</literal></tag-name>
<tag-desc>
allows to set version 1 cookies
and log the received cookies;
</tag-desc>

<tag-name><literal>log</literal></tag-name>
<tag-desc>
prohibits to set cookies
but allows to log the received cookies;
</tag-desc>

<tag-name><literal>off</literal></tag-name>
<tag-desc>
prohibits to set cookies and log the received cookies.
</tag-desc>

</list>
</para>

</directive>


<directive name="userid_domain">
<syntax><value>name</value> | <literal>none</literal></syntax>
<default>none</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Defines a domain for which the cookie is set.
The parameter <literal>none</literal> disables setting a domain for a cookie.
</para>

</directive>


<directive name="userid_expires">
<syntax><value>time</value> | <literal>max</literal></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Sets a time during which a browser should keep the cookie.
The parameter <literal>max</literal> sets the time to
“<literal>31 Dec 2037 23:55:55 GMT</literal>”.
This is the maximum time understood by old browsers.
</para>

</directive>


<directive name="userid_name">
<syntax><value>name</value></syntax>
<default>uid</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Sets a cookie name.
</para>

</directive>


<directive name="userid_p3p">
<syntax><value>string</value></syntax>
<default/>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Sets a value for the <header>P3P</header> header field that will be
sent along with a cookie.
</para>

</directive>


<directive name="userid_path">
<syntax><value>path</value></syntax>
<default>/</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Defines a path for which the cookie is set.
</para>

</directive>


<directive name="userid_service">
<syntax><value>number</value></syntax>
<default>IP address of the server</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Identifies the service that set a cookie.
For version 1 cookies the default value is zero.
For version 2 cookies the default value is an IP address of the server.
</para>

</directive>

</section>

</module>
